### ISSUE TITLE
💡 [REQUEST] - Add Splash Screen 

### ISSUE THREAD

**Issue by Vimalraj-Vijay** [Vimalraj-Vijay/Flutter-Shopping-app#27]
### Start Date

Aug/21/2022

### Implementation PR

Update this PR https://github.com/Vimalraj-Vijay/Flutter-Shopping-app/pull/25

### Summary

Add Splash Screen Which has to show the app logo

### Basic Example

Mostly all apps

### Drawbacks

App Logo not defined

**Comment by samitkapoor** [comment]
@Vimalraj-Vijay May I work on this issue?
If the app logo is not defined yet, I can place a dummy image, and later you can fill in the path to the app logo instead of the dummy image.

**Comment by Vimalraj-Vijay** [comment]
@samitkapoor Thanks for asking, but this issue already taken by our deverloper. And soon this repo will be changed to private.

**Comment by Vimalraj-Vijay** [comment]
@samitkapoor  Yeah sure you can takeup this change and please raise a PR for this
